#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"

# Source utils and consts
source "$SCRIPT_DIR/utils"
source "$SCRIPT_DIR/consts"

# Use a standardized git log command for previewing branch commits
PREVIEW_CMD='git log --color=always --decorate-refs-exclude=refs/tags --pretty=format:"%Cgreen%<(13)%cr%Creset %C(bold blue)%<(16)%an%Creset %C(auto)%d%Creset %s" -10 {1}'

# Display branches sorted by creation date and let user select one to checkout
selected_branch=$(git for-each-ref --sort='-creatordate' --format='%(if)%(HEAD)%(then)* %(else)  %(end)%(refname:short)' refs/heads/ |
    fzf --ansi --height 10 \
        --bind='tab:toggle-preview' \
        --preview-window hidden,right,60% \
        --preview "$PREVIEW_CMD")

# If a branch was selected, check it out
if [ -n "$selected_branch" ]; then
    # Remove leading spaces and asterisks
    selected_branch=$(echo "$selected_branch" | sed 's/^[ *]*//')

    echo "Checking out: $selected_branch"
    git checkout "$selected_branch"
else
    echo "Checkout cancelled"
    exit 1
fi
