#!/usr/bin/env bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
PARENT_DIR="$(dirname "$SCRIPT_DIR")"

# Source utils and consts from parent directory
source "$PARENT_DIR/utils"
source "$PARENT_DIR/consts"

if [ "$1" == "--version" ]; then
    echo "glogm version 1.2"
    echo "https://github.com/DanielKag/glogm"
    exit 0
fi

base_branch=$(git_main_branch)
remote_base_branch="origin/$base_branch"
current_branch=$(git rev-parse --abbrev-ref HEAD)

command_head="git -c color.ui=always log HEAD \
            --decorate-refs-exclude=refs/tags --abbrev-commit \
            --pretty=format:'%C(bold dim cyan)%h%Creset %Cgreen%<(13)%cr%Creset %C(bold blue)%<(16)%an%Creset %s %C(auto)%d%Creset'"

command_master="git -c color.ui=always log $remote_base_branch \
            --decorate-refs-exclude=refs/tags --abbrev-commit \
            --pretty=format:'%C(bold dim cyan)%h%Creset %Cgreen%<(13)%cr%Creset %C(bold blue)%<(16)%an%Creset %s %C(auto)%d%Creset'"

header=$(printf "<Tab>    Toggle commit diff\n<Enter>  See commit in github\n<R> Refresh\n← →      Choose branch")
head_prompt="${INVERT}${current_branch} (HEAD) ${NORMAL} ${remote_base_branch}"
base_prompt="${current_branch} (HEAD) ${INVERT}${remote_base_branch}${NORMAL}"
eval "echo '$head_prompt'; $command_head" |
    fzf --ansi --no-sort --exact \
        --header "$header" \
        --header-lines=1 \
        --reverse \
        --bind='tab:toggle-preview' \
        --bind "R:reload(git fetch && echo '$base_prompt'; $command_master)" \
        --bind "left:reload(echo '$head_prompt'; $command_head)" \
        --bind "right:reload(echo '$base_prompt'; $command_master)" \
        --preview-window right \
        --preview-window hidden \
        --preview 'git show {1} | delta' |
    cut -d\  -f 1 |
    openGithubCommitOnRemote
